<div class="panel panel-info">
    <div class="panel-heading">Information
        <h6 class="pull-right"><a href="dashboard">Close</a></h6>
    </div>
    <div class="panel-body">
        @if($student_data)
            @if($student_data[0]['status'] == 1)
                <table>
                    <tr>
                        <td>Serial No. : </td>
                        <td> </td>
                        <td>{{ $student_data[0]['serial_no'] }}</td>
                    </tr>
                    <tr>
                        <td>Student Name : </td>
                        <td> </td>
                        <td>{{ $student_data[0]['student_name'] }}</td>
                    </tr>
                    <tr>
                        <td>Certificate : </td>
                        <td> </td>
                        <td>{{ $student_data[0]['certificate_filename'] }}</td>
                    </tr>
                </table>
                <br>
                <br>
                <?php
                    $path = '/webapp/pdf'.'/'.$student_data[0]['certificate_filename'];   
                ?> 
                <iframe src="<?= asset($path) ?>" width="700px" height="400px"  />
            
            @elseif($student_data[0]['status'] == 0) 
                <h5>You scanned a correct  QR code , but the document is not active & valid any longer. <a href="/webapp/dashboard">Click Here</a> to scan again</h5>
            @endif

        @else
            <h5>The QR Code you scanned is not a Secured QR generated by this system. Kindly scanned one of our Secured QR only <a href="/webapp/dashboard">Click Here</a> to Scan Again.</h5>
        @endif

    </div>
</div>
